/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Customers: typeof import('./components/Customers/index.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabButtons: typeof import('./components/TabButtons.vue')['default']
    TheButton: typeof import('./components/TheButton.vue')['default']
    TheCard: typeof import('./components/TheCard.vue')['default']
    TheDatePicker: typeof import('./components/TheDatePicker.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheMenu: typeof import('./components/TheMenu.vue')['default']
    TheSearch: typeof import('./components/TheSearch.vue')['default']
    TheSelect: typeof import('./components/TheSelect.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
    TheSwitch: typeof import('./components/TheSwitch.vue')['default']
    TheTable: typeof import('./components/TheTable.vue')['default']
  }
}
