/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: (typeof import('./components/TheCard.vue'))['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
    ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElEmpty: (typeof import('element-plus/es'))['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: (typeof import('element-plus/es'))['ElOption']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElRadio: (typeof import('element-plus/es'))['ElRadio']
    ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton']
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    ElUpload: (typeof import('element-plus/es'))['ElUpload']
    PreviewImg: (typeof import('./components/PreviewImg.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabButtons: typeof import('./components/TabButtons.vue')['default']
    TheButton: typeof import('./components/TheButton.vue')['default']
    TheCard: typeof import('./components/TheCard.vue')['default']
    TheDatePicker: typeof import('./components/TheDatePicker.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheMenu: typeof import('./components/TheMenu.vue')['default']
    TheSearch: typeof import('./components/TheSearch.vue')['default']
    TheSelect: typeof import('./components/TheSelect.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
    TheSwitch: typeof import('./components/TheSwitch.vue')['default']
    TheTable: typeof import('./components/TheTable.vue')['default']
  }
}
